project:
  type: website
  output-dir: docs

website:
  title: "GEO 511 Final Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
  page-footer:
    left: "Â© 2025 Alan Vlakancic"
    right: "GEO511"
format:
  html:
    theme: darkly
    highlight: monochrome
    toc: true
    toc-location: left
    toc-depth: 4
    code-fold: true
    code-summary: "Show code"
    smooth-scroll: true
    css: styles.css
    include-after-body: include/after_body.html
